### ISSUE TITLE
Two different occasional errors

### ISSUE THREAD

**Issue by Federico-Agostinis** [Jiefei-Wang/SharedObject#2]
Hi, thanks for your usefull work. I'm using this package to massively parallelize a dimensionality reduction model.
I occasionaly recive these two error:
`Error in checkForRemoteErrors(val) : 
one node produced an error: Cannot find the information of data 7683294875353088`
Generally i recive it when i run the same model multiple time and i solve it by closing and reopening R but i don't know why it occurs. Obviously the number chenges every time.
The second error is: 
`terminating with uncaught exception of type Rcpp::LongjumpException`
this occurs also occasionaly.
Do you know how could I solve these errors?

**Comment by Jiefei-Wang** [comment]
Thanks for your report. I also occasionally receive errors from the package daily build report from Bioconductor, but I am still struggling to reproduce the bug. What you have encountered might be related to the error on the build report.  Would you be able to provide your session info and, if possible, an example code so that I can locate the bug?  Thank you!

**Comment by Jiefei-Wang** [comment]
These two issues are possibly fixed at 9dbfddb457057d0922a2f37b001dc2cfb15c42de
