### ISSUE TITLE
Problems with operation on big matrix

### ISSUE THREAD

**Issue by Federico-Agostinis** [Jiefei-Wang/SharedObject#3]
Goodmorning and thank you again for your work.
I found some problem sharing big matrix when they came from operation on other matrix.
I reproduced the error.

This should work.
This is more or less the dimension of my real use matrix, but I would like to use this packeage with bigger matrix, up to 1e6*1e4
 ```
library(SharedObject)
mat <- matrix(rpois(3e5*1000,1000),nrow=3e5)
str(mat)
shared_mat <- share(mat)
```
This should not work 
```
mat2 <-log1p(mat)
shared2 <- share(mat2)
```
This should not work either
```
mat3 <- mat
mat3[1,1] <- 1
shared3 <- share(mat3)
```
the cause is not the str() of the matrix
```
mode(mat3) <- "numeric"
str(mat3)
shared3 <- share(mat3)
```
Part of the cause could be the dimension of the matrix
```
mat4 <- matrix(rpois(2e5*1000,1000),nrow=2e5)
shared4<- share(log1p(mat4))
```

I hope this will help in finding the problem.
Thank you.

**Comment by Jiefei-Wang** [comment]
Hi @fedeago , Thanks for letting me know the issue. Could you please show me the message you get when you are not able to run the code? Without involving more detail, my guess is that you might hit the size limit of allocable memory on your system. 

`mat` will take 1.2GB and  `mat2` takes 2.4GB. Sharing them requires additional 1.2+2.4GB memory. Therefore, you need 7.2GB available memory in total for running your first two code blocks. 

I have tried your code on Ubuntu with 6GB memory. The R process gets automatically killed because of insufficient memory. If you are using Ubuntu, please try to run the code on a terminal and see if you get the message `killed` in the terminal. If so, the "bug" is our budget and unfortunately there is not too much we can do:). If you are not using Ubuntu or you see a different message, please let me know the detail of it so I can try to reproduce the problem.

**Comment by Federico-Agostinis** [comment]
Sorry, I forget the message...
```
Error in C_createSharedMemory(x, dataInfo) :
  Can't create a shared object, data ID 8321771038048256, has key:0
Invalid argiment
Warning message:
In n * h : NAs produced by integer overflow
```
That's the reason why I tried to change the structure from integer to numeric from integer to numeric, but it didn't work.
I am using it on ubuntu with 16GB of RAM and an Ubuntu server with 500GB of RAM so I don't think is a memory issue. If you run the second chunck removing "mat" from your environment and calling gc() you shuold have the same error. It seems to me that it happens when you modify some value , otherwise the second and the fifth chunck should work in the same way.

**Comment by Jiefei-Wang** [comment]
Thank you @fedeago for the details, the message means you are using a quite out-dated version of SharedObject because this message format has been removed since 1.1.1. I can reproduce the same error at 1.1.0 but not at the latest version. This bug may have been fixed unintentionally when I was working on the bug report you gave me a month before:). The latest version should be on the devel Bioconductor repository. Please update your package and see if it fixes your problem.

**Comment by Federico-Agostinis** [comment]
thank you. I was waiting for the new stable bioconductor version. It should be out today so I will try.

**Comment by Federico-Agostinis** [comment]
Hi, with the 1.2.2 version all works, so the problem is fixed. Thank you again.

**Comment by Jiefei-Wang** [comment]
@fedeago  Glad to hear it. Have a good day :)
